### ISSUE TITLE
redmine 4.1.x error for issues list page

### ISSUE THREAD

**Issue by yurmala** [Legomegger/custom_field_label#1]
ActionView::Template::Error (undefined method `custom_field_name_tag_bold' for #<#<Class:0x00005608d103bf58>:0x00005608d03e9638>
Did you mean?  custom_field_name_tag):
     9: <% split_on = (custom_field_values.size / 2.0).ceil - 1 %>
    10: <% custom_field_values.each do |value| %>
    11:         <% if value.custom_field.field_format == 'label'%>
    12:             <p><%= custom_field_name_tag_bold(value.custom_field) %></p>
    13:             <% else %>
    14:             <p><%= custom_field_tag_with_label :issue, value, :required => @issue.required_attribute?(value.custom_field_id) %></p>
    15:             <% end %>

**Comment by Legomegger** [comment]
yes thanks, ive fixed it now it works! Thank you!
